name: WPCS Check

on: pull_request

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: WPCS Check
          uses: 10up/wpcs-action@stable
          with:
            use_local_config: 'true'
            enable_warnings: 'false'
            extra_args: '--report-json=./phpcs.json'
        - name: Update summary
          run: |
            npm i -g github:10up/phpcs-json-to-md
            if [ -f ./phpcs.json ]; then
              phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
              cat phpcs.md >> $GITHUB_STEP_SUMMARY
            else
              echo "⚠️ PHPCS JSON report was not generated." >> $GITHUB_STEP_SUMMARY
            fi
          if: always()
